services:
  sge.postgres:
    image: postgres:latest
    container_name: sge_postgres
    environment:
      POSTGRES_DB: sgedb
      POSTGRES_USER: sgeuser
      POSTGRES_PASSWORD: sgepassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sge_network

  sge.api:
    image: sge.api
    build:
      context: .
      dockerfile: SGE.API/Dockerfile
    container_name: sge_api
    ports:
      - "5000:80"
    depends_on:
      - sge.postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=sge.postgres;Database=sgedb;Username=sgeuser;Password=sgepassword
    networks:
      - sge_network

volumes:
  postgres_data:

networks:
  sge_network:
    driver: bridge
